---
title: "mapas_selecionados"
author: "Fernando Almeida Barbalho"
date: '2024-05-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(geobr)
library(readxl)
library(basedosdados)
library(viridis)
library(sf)
library(ggrepel)
library(colorspace)
library(patchwork)
library(parcats)
library(plotly)
library(DT)
library(readr)
library(easyalluvial)


###Dados
 regioes_saude <- readRDS("regioes_saude.RDS")

dataset_analise <- readRDS("dataset_analise_2021.RDS")

dataset_analise$munuf<- paste(dataset_analise$mun_res_nome.x,dataset_analise$uf.x,sep = "-")


#Subsititui o valor do gasto percentual de Brasília pelo gasto percentual do DF
#O gasto percentual do DF é calculado a partir de planilha montada com dados trazidoso do MEU SICONFI
#Referência ano 2021, para gastos liquidados

perc_brasilia_DF<- 6.734319894

dataset_analise<-
  dataset_analise %>%
  mutate(perc.x = ifelse(munic_res=="530010", perc_brasilia_DF, perc.x),
         perc.y = ifelse(codufmun =="530010", perc_brasilia_DF, perc.y ))
  
  
# dataset_analise %>%
#   mutate(perc.x = ifelse(cod_cidade.x=="5300108", perc_brasilia_DF, perc.x),
#          perc.y = ifelse(cod_cidade.y =="5300108", perc_brasilia_DF, perc.y ))


agrupamento_municipio_cluster<-readRDS("agrupamento_municipio_2021.RDS")

load("dados_auxiliares.RData")

# dataset_analise<-
# dataset_analise %>%
#   inner_join(
#     pop_municipios %>%
#       select(id_municipio,
#              sigla_uf) 
#   ) %>%
#   mutate(uf.x = sigla_uf,
#          uf.y = sigla_uf) %>%
#   select(-sigla_uf)

de_para_hierarquia <- read_delim("de_para_hierarquia.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)


pop_municipios$pop_cut<- cut(pop_municipios$populacao, 
                             breaks = c(0,
                                        2000,
                                        5000,
                                        10000,
                                        20000,
                                        50000,
                                        100000,
                                        500000,
                                        max(pop_municipios$populacao)), 
                             labels= c("0-2.000",
                                       "2.001-5.000",
                                       "5.000-10.000",
                                       "10.001-20.000",
                                       "20.001-50.000",
                                       "50.001-100.000",
                                       "100.001-500.000",
                                       ">500.000"))

municipios_seat<- cbind(municipios_seat, st_coordinates(st_centroid(municipios_seat)))

municipios_seat<-
municipios_seat %>%
  inner_join(
    pop_municipios %>%
      mutate(code_muni=  as.numeric(id_municipio)) %>%
      select(code_muni, populacao, pop_cut)
  )





REGIC_trabalho$nome_nivel_hierarquia_ordenado<-
factor(REGIC_trabalho$nome_nivel_hierarquia, levels = unique(REGIC_trabalho$nome_nivel_hierarquia[order(REGIC_trabalho$nivel_hierarquia)]))


agrupamento_municipio<-
    dataset_analise %>%
      filter(
             deslocamento ==1) %>%
      group_by(munic_res) %>%
      summarise(
        numero_internacoes = n()
      ) %>%
      mutate(code_muni = munic_res,
             tipo_deslocamento = "saida" ) %>%
      bind_rows(
        dataset_analise %>%
          filter(
                 deslocamento ==1) %>%
          group_by(codufmun) %>%
          summarise(
            numero_internacoes = n()
          ) %>%
          mutate(code_muni = codufmun,
                 tipo_deslocamento = "entrada"),
        dataset_analise %>%
          filter(
                 deslocamento ==0) %>%
          group_by(codufmun) %>%
          summarise(
            numero_internacoes = n()
          ) %>%
          mutate(code_muni = codufmun,
                 tipo_deslocamento = "local")
      ) %>%
  group_by(code_muni, tipo_deslocamento) %>%
  summarise(
    total_internacoes = sum(numero_internacoes)
  ) %>%
  ungroup()

agrupamento_municipio<-
agrupamento_municipio %>%
  tidyr::pivot_wider(names_from = tipo_deslocamento, values_from = total_internacoes) %>%
  mutate(liquido = ifelse(is.na(entrada),0,entrada)+
           ifelse(is.na(local),0,local)-
           ifelse(is.na(saida),0,saida))

agrupamento_municipio<-
agrupamento_municipio %>%
  mutate(local = ifelse(is.na(local),0,local),
         saida = ifelse(is.na(saida),0,saida),
         entrada = ifelse(is.na(entrada),0,entrada),
         perc_saida = saida/(saida+local)*100,
         perc_entrada = entrada/(entrada+local)*100,
         perc_entrada = ifelse(is.nan(perc_entrada),0,perc_entrada))



municipios_seat<-
municipios_seat %>%
  mutate(code_muni_reduzido = as.character(code_muni),
         code_muni_reduzido = str_sub(code_muni,1,6)) %>%
  inner_join(
    agrupamento_municipio%>%
      rename(code_muni_reduzido = code_muni))


mun_sel_nivel_1A<-
  municipios_seat %>%
  inner_join(
    REGIC_trabalho%>%
      filter(nivel_hierarquia=="1A")%>%
      mutate(code_muni = cod_cidade))

mun_sel_nivel_1B<-
  municipios_seat %>%
  inner_join(
    REGIC_trabalho%>%
      filter(nivel_hierarquia=="1B")%>%
      mutate(code_muni = cod_cidade))


mun_sel_nivel_1C<-
  municipios_seat %>%
  inner_join(
    REGIC_trabalho%>%
      filter(nivel_hierarquia=="1C")%>%
      mutate(code_muni = cod_cidade))


mun_sel_nivel_2A<-
  municipios_seat %>%
  inner_join(
    REGIC_trabalho%>%
      filter(nivel_hierarquia=="2A")%>%
      mutate(code_muni = cod_cidade))

#### funções
busca_municipio_regic<- function(){
  
  municipios<-
  REGIC_trabalho %>%
    inner_join(
      municipios_seat %>%
        mutate(cod_cidade= code_muni)
      ) %>%
    select(name_muni,uf ) %>%
    mutate(name_muni = paste(name_muni, uf, sep = "-")) %>%
    arrange(name_muni)
  
  sort(unique(municipios$name_muni))
}


busca_hierarquia_regic<- function(){
  unique(REGIC_trabalho$nome_nivel_hierarquia_ordenado)
  
}

plot_mapa_entrada_saida <- function (tipo_es, mun_es, somente_dados= FALSE){
  
  muni_sel<-
    municipios_seat %>%
    mutate(name_muni = paste(name_muni,abbrev_state, sep = "-")) %>%
    filter(name_muni %in% mun_es) %>%
    inner_join(
      REGIC_trabalho %>%
        mutate(code_muni = cod_cidade)
    )
  
  
  # muni_sel<-
  #   muni_sel %>%
  #   filter(!(nivel_hierarquia %in% c("1A","1B","1C","2A")))
  
  
  if (tipo_es=="e"){
    texto_legenda <- "% de pacientes internados de outros municípios"
    var_fill<- "perc_entrada"
    
  } else {
    texto_legenda <- "% de pacientes internados em outros municípios"
    var_fill<- "perc_saida"
  }
  
  dados<-
    municipios_seat %>%
    mutate(code_muni = str_sub(as.character(code_muni),1,6)) %>%
    inner_join(
      REGIC_trabalho%>%
        mutate(code_muni = str_sub(as.character(cod_cidade),1,6))
    )
  
  if (somente_dados){
    return(dados)
  }
  
  
  dados %>%
    ggplot()+
    geom_sf(data = estados_mapa, fill=NA, color="#808080")+
    geom_sf(aes( fill= !!sym(var_fill)),pch=21, color="#444444", size=0.8, alpha=0.6)+
    geom_sf(data= mun_sel_nivel_1A, aes( fill= !!sym(var_fill)),pch=21, color="#444444", size=1, alpha=1)+
    geom_sf(data= mun_sel_nivel_1B, aes( fill= !!sym(var_fill)),pch=21, color="#444444", size=1, alpha=1)+
    geom_sf(data= mun_sel_nivel_1C, aes( fill= !!sym(var_fill)),pch=21, color="#444444", size=1, alpha=1)+
    geom_sf(data= mun_sel_nivel_2A, aes( fill= !!sym(var_fill)),pch=21, color="#444444", size=1, alpha=1)+
    geom_sf(data= muni_sel, aes( fill= !!sym(var_fill)),pch=21, color="white", size=1, alpha=1)+
    # geom_text_repel(data = mun_sel_nivel_1A,aes(x=X, y=Y, label= name_muni),fontface = "bold", color="white",size=2.5)+
    # geom_text_repel(data = mun_sel_nivel_1B,aes(x=X, y=Y, label= name_muni),fontface = "bold", color="white",size=2.5)+
    # geom_text_repel(data = mun_sel_nivel_1C,aes(x=X, y=Y, label= name_muni),fontface = "bold", color="white",size=2.5)+
    # geom_text_repel(data = mun_sel_nivel_2A,aes(x=X, y=Y, label= name_muni),fontface = "bold", color="white", force =2,size=2.5)+
    geom_text_repel(data = muni_sel,aes(x=X, y=Y,
                                        label= str_wrap(
                                          str_c(name_muni,
                                                round(!!sym(var_fill),2),
                                                "%",
                                                sep = " "
                                          )
                                          ,20)
    ),fontface = "bold", color="white")+
    scale_fill_continuous_sequential(palette= "Heat 2")+
    scale_color_continuous_sequential(palette= "Heat 2")+
    labs(
      fill= str_wrap(texto_legenda,15) 
    )+
    theme_light() +
    theme(
      panel.background = element_rect(fill = "black"),
      panel.grid = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      strip.background = element_rect(fill = "#505050"),
      strip.text = element_text(color = "white"),
      axis.text = element_blank()
    )+
    facet_wrap(nome_nivel_hierarquia_ordenado~.)
  
  
}

busca_todos_municipios<- function(){
  
  .data<- municipios
  
  .data$munuf<- paste(.data$name_muni, .data$abbrev_state, sep = "-")
  #sort(unique(dataset_analise$munuf))
  sort(.data$munuf)
}

busca_codigo_municipio<- function(nome_uf_mun, seis_digitos = TRUE){
  
  municipios_sel<-
  municipios %>%
    mutate(uf_mun = paste(name_muni, abbrev_state, sep="-")) %>%
    filter(uf_mun %in% nome_uf_mun) %>%
    select(code_muni)
  
  
  if(seis_digitos){
    municipios_sel$code_muni<- substr(municipios_sel$code_muni,1,6)
  }
  
  return(as.character(municipios_sel$code_muni))
  
}

```


```{r fig.width=20, fig.height=10, fig.dpi=500}


code_muni <- 431490
municipio_selecionado<- 431490

muni_sel<- 
  dataset_analise %>%
  filter(deslocamento ==1,
         codufmun==	municipio_selecionado) %>%
  group_by(codufmun,nome_nivel_hierarquia_ordenado.y, uf.y) %>%
  summarise(quantidade = n()) %>%
  rename(code_muni= codufmun,
         hierarquia = nome_nivel_hierarquia_ordenado.y,
         uf = uf.y) %>%
  mutate(tipo_deslocamento  = "destino",
         distancia = 0) %>%
  bind_rows(
    dataset_analise %>%
      filter(deslocamento ==1,
             codufmun==	municipio_selecionado) %>%
      group_by(munic_res,nome_nivel_hierarquia_ordenado.x, uf.x) %>%
      summarise(
        quantidade = n(),
        distancia =min(distancia)
      ) %>%
      ungroup() %>%
      rename(code_muni= munic_res,
             hierarquia = nome_nivel_hierarquia_ordenado.x,
             uf=uf.x)%>%
      mutate(tipo_deslocamento  = "origem")
  )



muni_sel_posicao<-
  dataset_analise %>%
  dplyr::filter(deslocamento ==1,
                codufmun==	municipio_selecionado)%>%
  distinct(codufmun, mun_res_lat.x, mun_res_lat.y, mun_res_lon.x, mun_res_lon.y,distancia)


muni_sel_posicao<-
  municipios_seat %>%
  mutate(code_muni = str_sub(as.character(code_muni),1,6)) %>%
  inner_join(
    muni_sel_posicao %>%
      rename(code_muni= codufmun)
  )



xmin<- min(min(muni_sel_posicao$mun_res_lon.x), min(muni_sel_posicao$mun_res_lon.y)) -1
xmax <- max(max(muni_sel_posicao$mun_res_lon.x), max(muni_sel_posicao$mun_res_lon.y)) +1


ymin<- min(min(muni_sel_posicao$mun_res_lat.x), min(muni_sel_posicao$mun_res_lat.y)) -1
ymax <- max(max(muni_sel_posicao$mun_res_lat.x), max(muni_sel_posicao$mun_res_lat.y)) +1

g1_entrada<<-
  municipios_seat %>%
  mutate(code_muni = str_sub(as.character(code_muni),1,6)) %>%
  inner_join(
    muni_sel
  ) %>%
  ggplot()+
  geom_sf(data = estados_mapa, fill=NA, color="lightgreen")+
  geom_curve(data=muni_sel_posicao, aes(x=mun_res_lon.x,y=mun_res_lat.x,xend=mun_res_lon.y,yend=mun_res_lat.y, colour= distancia),
             curvature = -.25, ncp = 800,size = 1)+
  geom_sf(fill="white",size=1.9,pch=21, color="#444444")+
  scale_fill_discrete_qualitative(palette="dark2")+
  scale_color_continuous_sequential(palette= "Heat 2")+
  coord_sf(xlim = c(xmin,xmax), ylim=c(ymin,ymax))+
  labs(
    fill= "",
    color = "Distância",
    title = "Deslocamento de pacientes com destino a Porto Alegre",
    subtitle = "Distâncias percorridas em Km",
    caption =  "Fonte: Datasus/STN. Elaboração própria"
  )+
  theme_light() +
  theme(
    panel.background = element_rect(fill = "black"),
    panel.grid = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    strip.background = element_rect(fill = "#505050"),
    strip.text = element_text(color = "white"),
    axis.text = element_blank()
    
  ) 

muni_sel_foco<-
  municipios_seat %>%
  mutate(code_muni = str_sub(as.character(code_muni),1,6)) %>%
  inner_join(
    muni_sel%>%
      filter(code_muni==municipio_selecionado)
  ) %>%
  mutate(quantidade = quantidade *10)

muni_sel_repel<-
  municipios_seat %>%
  mutate(code_muni = str_sub(as.character(code_muni),1,6)) %>%
  inner_join(muni_sel) %>%
  slice_max(order_by = quantidade, n=0)




muni_sel<-
  muni_sel%>%
  filter(code_muni!=municipio_selecionado)


set.seed(1972)

g2_entrada<<-
  municipios_seat %>%
  mutate(code_muni = str_sub(as.character(code_muni),1,6)) %>%
  inner_join(
    muni_sel
  ) %>%
  mutate(quantidade = quantidade *10) %>%
  ggplot()+
  geom_sf( aes(fill=quantidade),pch=21, color="#444444", size=2, show.legend = TRUE)+
  geom_sf( data= muni_sel_foco, aes(size=quantidade),pch=21, color="#444444", fill="white")+
  geom_sf(data= regioes_saude, fill= NA, color = "#505050")+
  geom_sf(data = estados_mapa, fill=NA, color="lightgreen")+#505050
  geom_text_repel(data = muni_sel_repel,
                  aes(x=X, y=Y, label= str_wrap(paste(name_muni,":",quantidade),10)), 
                  color = "white", 
                  fontface = "bold",
                  show.legend = TRUE,
                  force_pull = 0,
                  nudge_x = 3)+
  scale_fill_continuous_sequential(palette= "Heat", trans= "log2" )+
  coord_sf(xlim = c(xmin,xmax), ylim=c(ymin,ymax))+
  labs(
    fill = str_wrap("Saídas",15),
    size= str_wrap("Entradas",15),
    title = "Deslocamento de pacientes com destino a Porto Alegre",
    subtitle = "Número de internações por tipo de deslocamento",
    caption =  "Fonte: Datasus/STN. Elaboração própria"

  )+
  theme_light() +
  theme(
    panel.background = element_rect(fill = "black"),
    panel.grid = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    strip.background = element_rect(fill = "#505050"),
    strip.text = element_text(color = "white"),
    axis.text = element_blank(),
    legend.key = element_rect(fill = "#15202B")
    
  ) 





library(patchwork)

g1_entrada


ggsave("mapa_distancias.png", dpi = 500, width = 8, height = 6, units = "in")
```

```{r fig.width=20, fig.height=10, fig.dpi=500}
g2_entrada

ggsave("mapa_quantidades.png", dpi = 500, width = 8, height = 6, units = "in")
```

```{r}
g1_entrada + g2_entrada

ggsave("mapa_combinado.png", dpi = 500, width = 8, height = 6, units = "in")
```

